### ISSUE TITLE
ADC past PC5 do not show up.

### ISSUE THREAD

**Issue by ggurov** [rusefi/fw-custom-mega100#5]
On some variants, perhaps not 100 pin, there are ADC inputs past PC5, into the PF range, however, the do not show up in the generated list adc_channel_e_list,

in fact, none of the existing MCU's seem to expose PF+ adcs.

**Comment by rusefillc** [comment]
PC6 is not an ADC input

@ggurov please provide one exact example of an ADC1/ADC2 pin which does not show up

![image](https://github.com/user-attachments/assets/c92e17bf-0f60-4d4a-8de4-c74be26c5b2a)

**Comment by ggurov** [comment]
right, PC6 is not an analog input, that's just where port C's adc end,

however, there's PF3-PF10 that are ADCS on 144+ packages:

![image](https://github.com/user-attachments/assets/8e968554-2201-4e80-9dc4-cc53a65636ce)

oh, is ADC3 special ? cause all of PF ports are ADC3

**Comment by ggurov** [comment]
https://github.com/rusefi/rusefi/issues/785

**Comment by rusefillc** [comment]
> oh, is ADC3 special ? cause all of PF ports are ADC3

yes https://github.com/rusefi/rusefi/issues/2238
